version: "3.8"

services: 

    db:
        image: mysql
        restart: always
        volumes: 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: cape_codd


    pma:
        image: phpmyadmin
        restart: always
        ports: 
            - 80:80
        environment: 
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: secret
